/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivitySearchDescription: typeof import('./src/components/ActivitySearchDescription.vue')['default']
    ActivitySearchParameters: typeof import('./src/components/ActivitySearchParameters.vue')['default']
    AppMainNav: typeof import('./src/components/AppMainNav.vue')['default']
    BimodalSwitch: typeof import('./src/components/BimodalSwitch.vue')['default']
    BlockingUserActionRequiredModal: typeof import('./src/components/BlockingUserActionRequiredModal.vue')['default']
    CardTable: typeof import('./src/components/CardTable.vue')['default']
    CptvPlayer: typeof import('./src/components/cptv-player/CptvPlayer.vue')['default']
    CptvSingleFrame: typeof import('./src/components/CptvSingleFrame.vue')['default']
    CreateProjectModal: typeof import('./src/components/CreateProjectModal.vue')['default']
    DeviceBatteryLevel: typeof import('./src/components/DeviceBatteryLevel.vue')['default']
    DeviceName: typeof import('./src/components/DeviceName.vue')['default']
    DeviceRecordingOptions: typeof import('./src/components/DeviceRecordingOptions.vue')['default']
    DeviceSetupDefineMask: typeof import('./src/components/DeviceSetupDefineMask.vue')['default']
    DeviceSetupReferencePhoto: typeof import('./src/components/DeviceSetupReferencePhoto.vue')['default']
    DeviceTrapActionsSetup: typeof import('./src/components/DeviceTrapActionsSetup.vue')['default']
    GitReleaseInfoBar: typeof import('./src/components/GitReleaseInfoBar.vue')['default']
    HierarchicalTagSelect: typeof import('./src/components/HierarchicalTagSelect.vue')['default']
    HorizontalOverflowCarousel: typeof import('./src/components/HorizontalOverflowCarousel.vue')['default']
    IconCacophonyLogo: typeof import('./src/components/icons/IconCacophonyLogo.vue')['default']
    IconCacophonyLogoFull: typeof import('./src/components/icons/IconCacophonyLogoFull.vue')['default']
    ImageLoader: typeof import('./src/components/ImageLoader.vue')['default']
    InlineViewModal: typeof import('./src/components/InlineViewModal.vue')['default']
    JoinExistingProjectModal: typeof import('./src/components/JoinExistingProjectModal.vue')['default']
    LayeredDropdown: typeof import('./src/components/LayeredDropdown.vue')['default']
    LeaveProjectModal: typeof import('./src/components/LeaveProjectModal.vue')['default']
    LocationItemSummary: typeof import('./src/components/LocationItemSummary.vue')['default']
    LocationName: typeof import('./src/components/LocationName.vue')['default']
    LocationPicker: typeof import('./src/components/LocationPicker.vue')['default']
    LocationsOverviewTable: typeof import('./src/components/LocationsOverviewTable.vue')['default']
    MapWithPoints: typeof import('./src/components/MapWithPoints.vue')['default']
    NetworkConnectionAlertModal: typeof import('./src/components/NetworkConnectionAlertModal.vue')['default']
    OverflowingTabList: typeof import('./src/components/OverflowingTabList.vue')['default']
    ProjectInviteModal: typeof import('./src/components/ProjectInviteModal.vue')['default']
    ProjectVisitsSummary: typeof import('./src/components/ProjectVisitsSummary.vue')['default']
    RecordingsList: typeof import('./src/components/RecordingsList.vue')['default']
    RecordingViewActionButtons: typeof import('./src/components/RecordingViewActionButtons.vue')['default']
    RecordingViewLabels: typeof import('./src/components/RecordingViewLabels.vue')['default']
    RecordingViewMetadata: typeof import('./src/components/RecordingViewMetadata.vue')['default']
    RecordingViewNotes: typeof import('./src/components/RecordingViewNotes.vue')['default']
    RecordingViewTabs: typeof import('./src/components/RecordingViewTabs.vue')['default']
    RecordingViewTracks: typeof import('./src/components/RecordingViewTracks.vue')['default']
    RenameableLocationName: typeof import('./src/components/RenameableLocationName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrubberWrapper: typeof import('./src/components/ScrubberWrapper.vue')['default']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SpectrogramViewer: typeof import('./src/components/SpectrogramViewer.vue')['default']
    SwitchProjectsModal: typeof import('./src/components/SwitchProjectsModal.vue')['default']
    TagImage: typeof import('./src/components/TagImage.vue')['default']
    TooltipOnTruncation: typeof import('./src/components/TooltipOnTruncation.vue')['default']
    TracksScrubber: typeof import('./src/components/TracksScrubber.vue')['default']
    TrackTaggerRow: typeof import('./src/components/TrackTaggerRow.vue')['default']
    TwoStepActionButton: typeof import('./src/components/TwoStepActionButton.vue')['default']
    VisitsBreakdownList: typeof import('./src/components/VisitsBreakdownList.vue')['default']
    VisitsDailyBreakdown: typeof import('./src/components/VisitsDailyBreakdown.vue')['default']
    VisitsTimeline: typeof import('./src/components/VisitsTimeline.vue')['default']
    WizardStep: typeof import('./src/components/WizardStep.vue')['default']
    WizardStepList: typeof import('./src/components/WizardStepList.vue')['default']
  }
}
