/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ActivitySearchDescription: typeof import("./src/components/ActivitySearchDescription.vue")["default"];
    ActivitySearchParameters: typeof import("./src/components/ActivitySearchParameters.vue")["default"];
    BAlert: typeof import("bootstrap-vue-next")["BAlert"];
    BBadge: typeof import("bootstrap-vue-next")["BBadge"];
    BButton: typeof import("bootstrap-vue-next")["BButton"];
    BButtonGroup: typeof import("bootstrap-vue-next")["BButtonGroup"];
    BDropdown: typeof import("bootstrap-vue-next")["BDropdown"];
    BDropdownDivider: typeof import("bootstrap-vue-next")["BDropdownDivider"];
    BDropdownGroup: typeof import("bootstrap-vue-next")["BDropdownGroup"];
    BDropdownItem: typeof import("bootstrap-vue-next")["BDropdownItem"];
    BDropdownItemButton: typeof import("bootstrap-vue-next")["BDropdownItemButton"];
    BForm: typeof import("bootstrap-vue-next")["BForm"];
    BFormCheckbox: typeof import("bootstrap-vue-next")["BFormCheckbox"];
    BFormCheckboxGroup: typeof import("bootstrap-vue-next")["BFormCheckboxGroup"];
    BFormGroup: typeof import("bootstrap-vue-next")["BFormGroup"];
    BFormInput: typeof import("bootstrap-vue-next")["BFormInput"];
    BFormInvalidFeedback: typeof import("bootstrap-vue-next")["BFormInvalidFeedback"];
    BFormRadio: typeof import("bootstrap-vue-next")["BFormRadio"];
    BFormRadioGroup: typeof import("bootstrap-vue-next")["BFormRadioGroup"];
    BFormSelect: typeof import("bootstrap-vue-next")["BFormSelect"];
    BimodalSwitch: typeof import("./src/components/BimodalSwitch.vue")["default"];
    BInput: typeof import("bootstrap-vue-next")["BInput"];
    BLink: typeof import("bootstrap-vue-next")["BLink"];
    BlockingUserActionRequiredModal: typeof import("./src/components/BlockingUserActionRequiredModal.vue")["default"];
    BModal: typeof import("bootstrap-vue-next")["BModal"];
    BOffcanvas: typeof import("bootstrap-vue-next")["BOffcanvas"];
    BPopover: typeof import("bootstrap-vue-next")["BPopover"];
    BProgress: typeof import("bootstrap-vue-next")["BProgress"];
    BSpinner: typeof import("bootstrap-vue-next")["BSpinner"];
    CardTable: typeof import("./src/components/CardTable.vue")["default"];
    CptvPlayer: typeof import("./src/components/cptv-player/CptvPlayer.vue")["default"];
    CptvSingleFrame: typeof import("./src/components/CptvSingleFrame.vue")["default"];
    CreateProjectModal: typeof import("./src/components/CreateProjectModal.vue")["default"];
    CreateProxyDeviceModal: typeof import("./src/components/CreateProxyDeviceModal.vue")["default"];
    DeviceBatteryLevel: typeof import("./src/components/DeviceBatteryLevel.vue")["default"];
    DeviceName: typeof import("./src/components/DeviceName.vue")["default"];
    DeviceRecordingSetup: typeof import("./src/components/DeviceRecordingSetup.vue")["default"];
    DeviceSetupDefineMask: typeof import("./src/components/DeviceSetupDefineMask.vue")["default"];
    DeviceSetupReferencePhoto: typeof import("./src/components/DeviceSetupReferencePhoto.vue")["default"];
    GitReleaseInfoBar: typeof import("./src/components/GitReleaseInfoBar.vue")["default"];
    HierarchicalTagSelect: typeof import("./src/components/HierarchicalTagSelect.vue")["default"];
    HorizontalOverflowCarousel: typeof import("./src/components/HorizontalOverflowCarousel.vue")["default"];
    IconCacophonyLogo: typeof import("./src/components/icons/IconCacophonyLogo.vue")["default"];
    IconCacophonyLogoFull: typeof import("./src/components/icons/IconCacophonyLogoFull.vue")["default"];
    ImageLoader: typeof import("./src/components/ImageLoader.vue")["default"];
    InlineViewModal: typeof import("./src/components/InlineViewModal.vue")["default"];
    JoinExistingProjectModal: typeof import("./src/components/JoinExistingProjectModal.vue")["default"];
    LayeredDropdown: typeof import("./src/components/LayeredDropdown.vue")["default"];
    LeaveProjectModal: typeof import("./src/components/LeaveProjectModal.vue")["default"];
    LocationPicker: typeof import("./src/components/LocationPicker.vue")["default"];
    LocationsOverviewTable: typeof import("./src/components/LocationsOverviewTable.vue")["default"];
    LocationVisitSummary: typeof import("./src/components/LocationVisitSummary.vue")["default"];
    MapWithPoints: typeof import("./src/components/MapWithPoints.vue")["default"];
    NetworkConnectionAlertModal: typeof import("./src/components/NetworkConnectionAlertModal.vue")["default"];
    OverflowingTabList: typeof import("./src/components/OverflowingTabList.vue")["default"];
    ProjectInviteModal: typeof import("./src/components/ProjectInviteModal.vue")["default"];
    ProjectVisitsSummary: typeof import("./src/components/ProjectVisitsSummary.vue")["default"];
    RecordingsList: typeof import("./src/components/RecordingsList.vue")["default"];
    RecordingViewActionButtons: typeof import("./src/components/RecordingViewActionButtons.vue")["default"];
    RecordingViewLabels: typeof import("./src/components/RecordingViewLabels.vue")["default"];
    RecordingViewTracks: typeof import("./src/components/RecordingViewTracks.vue")["default"];
    RenameableLocationName: typeof import("./src/components/RenameableLocationName.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    ScrubberWrapper: typeof import("./src/components/ScrubberWrapper.vue")["default"];
    SectionHeader: typeof import("./src/components/SectionHeader.vue")["default"];
    SwitchProjectsModal: typeof import("./src/components/SwitchProjectsModal.vue")["default"];
    TagImage: typeof import("./src/components/TagImage.vue")["default"];
    TracksScrubber: typeof import("./src/components/TracksScrubber.vue")["default"];
    TrackTaggerRow: typeof import("./src/components/TrackTaggerRow.vue")["default"];
    TwoStepActionButton: typeof import("./src/components/TwoStepActionButton.vue")["default"];
    VisitsBreakdownList: typeof import("./src/components/VisitsBreakdownList.vue")["default"];
    VisitsDailyBreakdown: typeof import("./src/components/VisitsDailyBreakdown.vue")["default"];
    VisitsTimeline: typeof import("./src/components/VisitsTimeline.vue")["default"];
    WizardStep: typeof import("./src/components/WizardStep.vue")["default"];
    WizardStepList: typeof import("./src/components/WizardStepList.vue")["default"];
  }
}
