services:
  server:
    container_name: cacophony-api
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DBNAME: cacophonytest
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    ports:
      - "1080:1080"
      - "2008:2008"
      - "5432:5432"
      - "9001:9001"
      - "9229:9229"
    volumes:
      - ./api:/app/api
      - ./types:/app/types
      # Exclude the following folders
      - /app/api/docker-base/
      - /app/api/node_modules/
      - /app/api/sql/
