import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faUser,
  faGaugeHigh,
  faLocationDot,
  faMagnifyingGlass,
  faMicrochip,
  faCircleExclamation,
  faGear,
  faChartPie,
  faScrewdriverWrench,
  faRetweet,
  faPlus,
  faRightFromBracket,
  faEye,
  faEyeSlash,
  faTriangleExclamation,
  faQuestion,
  faBars,
  faChevronRight,
  faMoon,
  faMapMarkerAlt,
  faXmark,
  faTag,
  faFlag as faFlagSolid,
  faStar as faStarSolid,
  faDownload,
  faTrashCan,
  faLink,
  faCheck,
  faSpinner,
  faBackward,
  faRedoAlt,
  faForward,
  faPlay,
  faStepBackward,
  faStepForward,
  faEyedropper,
  faImage,
} from "@fortawesome/free-solid-svg-icons";

import {
  faClock,
  faCalendar,
  faFlag,
  faStar,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faUser,
  faGaugeHigh,
  faLocationDot,
  faMagnifyingGlass,
  faMicrochip,
  faCircleExclamation,
  faGear,
  faChartPie,
  faScrewdriverWrench,
  faRetweet,
  faPlus,
  faRightFromBracket,
  faEye,
  faEyeSlash,
  faTriangleExclamation,
  faQuestion,
  faBars,
  faChevronRight,
  faMoon,
  faMapMarkerAlt,
  faXmark,
  faClock,
  faCalendar,
  faTag,
  faFlag,
  faStar,
  faFlagSolid,
  faStarSolid,
  faDownload,
  faTrashCan,
  faLink,
  faCheck,
  faSpinner,
  faBackward,
  faRedoAlt,
  faForward,
  faPlay,
  faStepBackward,
  faStepForward,
  faEyedropper,
  faImage
);

export default FontAwesomeIcon;
